import { cva, type VariantProps } from 'class-variance-authority'
import type { ComponentPropsWithRef, ReactNode } from 'react'

/**
 * Fills, inks and states come from DESIGN-SPEC §7.4, generated by cva rather
 * than the old `.btn`/`.btn--*` recipes in index.css (task #22 — the last
 * blocker to a fully utility-only index.css for buttons, once index.css itself
 * is free to take the recipe deletion). Every variant has hover, active and
 * focus-visible — a hover-only affordance is invisible on the target device,
 * which has no hover. `not-disabled:` throughout because a disabled button
 * still matches `:hover`/`:active` in CSS; disabled is a flat colour swap on
 * the base classes instead — opacity is never used for it, since that would
 * destroy the measured contrast of everything underneath. Never white text on
 * `--accent` (1.99:1 with the *original* amber) — `--accent-ink` is tuned to
 * `--accent` itself, so a primary fill stays safe under any palette Design
 * ships behind those two tokens.
 */
const button = cva(
  // `btn` carries NO styles any more — the rule it named is gone from index.css
  // (Tailwind utilities below do the work). It stays on the element purely as
  // a selector hook, the same move Toast.tsx made for `.toast`: `audit.mjs`
  // reads `.btn` for cursor and 44px-target checks that have nothing to do
  // with which variant is on screen.
  'btn inline-flex items-center justify-center gap-2 flex-none min-h-touch px-4 rounded-md border border-transparent ' +
    'font-ui text-btn leading-[1.2] font-semibold select-none touch-manipulation cursor-pointer ' +
    'transition-[background-color,color,transform] duration-(--dur-fast) ease-standard active:scale-97 ' +
    'disabled:scale-100 disabled:cursor-not-allowed disabled:border-transparent disabled:bg-surface-4 disabled:text-text-disabled',
  {
    variants: {
      variant: {
        primary: 'bg-accent text-accent-ink hover:not-disabled:bg-accent-hover active:not-disabled:bg-accent-press',
        stop:
          'bg-danger-soft text-danger border-danger ' +
          'hover:not-disabled:bg-[color-mix(in_srgb,var(--danger-soft)_70%,var(--danger)_12%)] ' +
          'active:not-disabled:bg-[color-mix(in_srgb,var(--danger-soft)_60%,var(--danger)_20%)]',
        ghost:
          'bg-transparent text-text-2 border-border-control ' +
          'hover:not-disabled:bg-surface-3 hover:not-disabled:text-text-1 ' +
          'active:not-disabled:bg-surface-4 active:not-disabled:text-text-1',
        danger:
          'bg-danger-fill text-white ' +
          'hover:not-disabled:bg-[color-mix(in_srgb,var(--danger-fill)_88%,white)] ' +
          'active:not-disabled:bg-[color-mix(in_srgb,var(--danger-fill)_80%,black)]',
        quiet:
          'bg-transparent text-text-2 font-medium ' +
          'hover:not-disabled:bg-surface-3 hover:not-disabled:text-text-1 ' +
          'active:not-disabled:bg-surface-4 active:not-disabled:text-text-1',
      },
      /** Run/Stop and primary dialog actions. min-width keeps the control the
       *  same size across the Run→Stop swap so its neighbours never shift. */
      large: { true: 'min-h-touch-lg min-w-[96px]', false: '' },
      /** Still a 44px target, but visually secondary — for an action offered
       *  inside a dense row (the "New file" beside an empty folder). */
      compact: { true: 'px-2 text-meta', false: '' },
    },
    defaultVariants: { variant: 'quiet', large: false, compact: false },
  },
)

export type ButtonVariant = NonNullable<VariantProps<typeof button>['variant']>

export interface ButtonProps extends ComponentPropsWithRef<'button'> {
  variant?: ButtonVariant
  /** Run/Stop and primary dialog actions are 48px, not 44px. */
  large?: boolean
  /** Visually secondary at the same 44px target — a row's inline "New file". */
  compact?: boolean
  children?: ReactNode
}

export function Button({ variant = 'quiet', large, compact, className = '', children, ...rest }: ButtonProps) {
  return (
    <button
      type="button"
      // Which variant is on screen used to be readable off a `.btn--primary`
      // modifier class; that class no longer exists, so it is published as an
      // attribute instead — the same role `data-kind` plays on a toast.
      // `audit.mjs`'s amber-fill check reads this.
      data-variant={variant}
      className={button({ variant, large, compact }) + (className ? ' ' + className : '')}
      {...rest}
    >
      {children}
    </button>
  )
}

/** Square icon-only control: 44px box, 20px glyph — the box is the target. */
const iconButton = cva(
  // Same selector-hook move as `btn` above — `.icon-btn` names nothing in CSS
  // any more but is still what `audit.mjs` and the pixel-crop harness find.
  'icon-btn inline-grid place-items-center flex-none size-touch rounded-md text-[20px] leading-none text-text-2 ' +
    'touch-manipulation cursor-pointer transition-[background-color,color] duration-(--dur-fast) ease-standard ' +
    'hover:not-disabled:bg-surface-3 hover:not-disabled:text-text-1 ' +
    'active:not-disabled:bg-surface-4 active:not-disabled:text-text-1 ' +
    'disabled:text-text-disabled disabled:cursor-not-allowed',
)

export function IconButton({
  label,
  className = '',
  children,
  ...rest
}: ComponentPropsWithRef<'button'> & { label: string }) {
  return (
    <button
      type="button"
      aria-label={label}
      title={label}
      className={iconButton() + (className ? ' ' + className : '')}
      {...rest}
    >
      {children}
    </button>
  )
}
