/* Builds the test harness (not the module -- the module is consumed as TS source
 * by the app's own bundler).
 *
 *   1. copies content/templates/python-starter/** into template.generated.js so
 *      the harness runs the shipped template verbatim, byte for byte
 *   2. bundles harness/harness.js (+ the TS module) to harness/build/harness.js
 *   3. copies src/worker.js next to it, because the module resolves the worker
 *      with `new URL('./worker.js', import.meta.url)`
 *
 * Vite does step 3 by itself; esbuild has no worker support, hence the copy.
 */

import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '../..')
const templateDir = join(repo, 'content/templates/python-starter')
const buildDir = join(here, 'harness/build')

// --- 1. template -> template.generated.js -----------------------------------

function walk(dir) {
  const found = []
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) found.push(...walk(full))
    else found.push(full)
  }
  return found
}

const templateFiles = walk(templateDir)
  .filter((f) => f.endsWith('.py'))
  .map((f) => ({ path: relative(templateDir, f), content: readFileSync(f, 'utf8') }))
  // entry first, purely so the harness file list reads nicely
  .sort((a, b) => (a.path === 'main.py' ? -1 : b.path === 'main.py' ? 1 : a.path.localeCompare(b.path)))

if (!templateFiles.some((f) => f.path === 'main.py')) {
  throw new Error(`no main.py in ${templateDir}`)
}

writeFileSync(
  join(here, 'harness/template.generated.js'),
  `/* GENERATED by build.mjs from content/templates/python-starter -- do not edit.
 * Verbatim copies of the shipped template files. */
export const TEMPLATE = {
  label: 'python-starter template',
  entry: 'main.py',
  files: ${JSON.stringify(templateFiles, null, 2).replace(/\n/g, '\n  ')},
}
`,
)
console.log(`template.generated.js: ${templateFiles.map((f) => f.path).join(', ')}`)

// --- 2. bundle --------------------------------------------------------------

const candidates = [
  join(here, 'node_modules/.bin/esbuild'),
  join(repo, 'app/node_modules/.bin/esbuild'),
  join(repo, 'node_modules/.bin/esbuild'),
]
const esbuild = candidates.find((p) => existsSync(p))
if (!esbuild) {
  throw new Error(
    `esbuild not found. Looked in:\n  ${candidates.join('\n  ')}\n` +
      'Run `npm install` in runtimes/python/ (harness build only; the module itself needs no deps).',
  )
}

mkdirSync(buildDir, { recursive: true })
execFileSync(
  esbuild,
  [
    join(here, 'harness/harness.js'),
    '--bundle',
    '--format=esm',
    '--target=es2022',
    `--outfile=${join(buildDir, 'harness.js')}`,
  ],
  { stdio: 'inherit' },
)

// --- 3. worker next to the bundle ------------------------------------------

copyFileSync(join(here, 'src/worker.js'), join(buildDir, 'worker.js'))
console.log('harness/build/: harness.js, worker.js')
