/* Builds the test harness, and generates the two committed generated files.
 *
 *   1. src/bootstrap/*.java  ->  src/bootstrap.generated.ts
 *      The worker needs the bootstrap Java as strings. The .java files are the
 *      source of truth (they get syntax highlighting, and `npm run check`
 *      compiles them against a real Java 8 target); the .ts file is generated
 *      and COMMITTED, because the app consumes this module as TypeScript source
 *      with no build step of its own.
 *   2. content/templates/java-oop/** -> harness/template.generated.js
 *      so the harness runs the shipped template verbatim, byte for byte.
 *   3. bundles harness/harness.js (+ the TS module) to harness/build/harness.js
 *   4. copies src/jvm.worker.js next to it, because the module resolves the
 *      worker with `new URL('./jvm.worker.js', import.meta.url)`
 *   5. checks ecj.jar is at the harness web root
 *
 * Vite does step 4 by itself; esbuild has no worker support, hence the copy.
 *
 *   node build.mjs           build
 *   node build.mjs --check   fail if a generated file is out of date (for CI)
 */

import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '../..')
const templateDir = join(repo, 'content/templates/java-oop')
const buildDir = join(here, 'harness/build')
const checkOnly = process.argv.includes('--check')

let stale = 0

/** Writes only if the content changed; in --check mode reports instead. */
function emit(path, content) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null
  if (current === content) return
  if (checkOnly) {
    console.error(`OUT OF DATE: ${relative(repo, path)} -- run \`node build.mjs\``)
    stale++
    return
  }
  writeFileSync(path, content)
}

function walk(dir) {
  const found = []
  for (const name of readdirSync(dir).sort()) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) found.push(...walk(full))
    else found.push(full)
  }
  return found
}

// --- 1. bootstrap Java -> bootstrap.generated.ts ----------------------------

const bootstrapDir = join(here, 'src/bootstrap')
const bootstrapFiles = walk(bootstrapDir).filter((f) => f.endsWith('.java'))
if (!bootstrapFiles.length) throw new Error(`no .java files in ${bootstrapDir}`)

// Compiled flat in /str/, which has no directories, so basenames must be unique.
const basenames = bootstrapFiles.map((f) => relative(bootstrapDir, f))
const duplicates = basenames.filter((n, i) => basenames.indexOf(n) !== i)
if (duplicates.length) throw new Error(`duplicate bootstrap basenames: ${duplicates.join(', ')}`)
if (basenames.some((n) => n.includes('/'))) {
  throw new Error(`bootstrap sources must be flat (/str/ has no directories): ${basenames.join(', ')}`)
}

emit(
  join(here, 'src/bootstrap.generated.ts'),
  `/* GENERATED by build.mjs from src/bootstrap/*.java -- do not edit.
 *
 * The worker writes these into CheerpJ's /str/ mount and compiles them on first
 * load(). Edit the .java files and re-run \`node build.mjs\`; \`npm run check\`
 * fails if this file is stale.
 */

export const BOOTSTRAP_SOURCES: Record<string, string> = ${JSON.stringify(
    Object.fromEntries(
      bootstrapFiles.map((f) => [relative(bootstrapDir, f), readFileSync(f, 'utf8')]),
    ),
    null,
    2,
  )}
`,
)
console.log(`bootstrap.generated.ts: ${basenames.join(', ')}`)

// --- 2. template -> template.generated.js -----------------------------------

const ENTRY = 'app/Main.java'
const templateFiles = walk(templateDir)
  .filter((f) => f.endsWith('.java'))
  .map((f) => ({ path: relative(templateDir, f), content: readFileSync(f, 'utf8') }))
  // entry first, purely so the harness file list reads nicely
  .sort((a, b) => (a.path === ENTRY ? -1 : b.path === ENTRY ? 1 : a.path.localeCompare(b.path)))

if (!templateFiles.some((f) => f.path === ENTRY)) {
  throw new Error(`no ${ENTRY} in ${templateDir}`)
}

emit(
  join(here, 'harness/template.generated.js'),
  `/* GENERATED by build.mjs from content/templates/java-oop -- do not edit.
 * Verbatim copies of the shipped template files. */
export const TEMPLATE = {
  label: 'java-oop template',
  entry: '${ENTRY}',
  files: ${JSON.stringify(templateFiles, null, 2).replace(/\n/g, '\n  ')},
}
`,
)
console.log(`template.generated.js: ${templateFiles.map((f) => f.path).join(', ')}`)

if (checkOnly) {
  if (stale) process.exit(1)
  console.log('generated files are up to date')
  process.exit(0)
}

// --- 3. bundle --------------------------------------------------------------

const candidates = [
  join(here, 'node_modules/.bin/esbuild'),
  join(repo, 'runtimes/python/node_modules/.bin/esbuild'),
  join(repo, 'app/node_modules/.bin/esbuild'),
  join(repo, 'node_modules/.bin/esbuild'),
]
const esbuild = candidates.find((p) => existsSync(p))
if (!esbuild) {
  throw new Error(
    `esbuild not found. Looked in:\n  ${candidates.join('\n  ')}\n` +
      'Run `npm install` in runtimes/java/ (harness build only; the module itself needs no deps).',
  )
}

mkdirSync(buildDir, { recursive: true })
execFileSync(
  esbuild,
  [
    join(here, 'harness/harness.js'),
    '--bundle',
    '--format=esm',
    '--target=es2022',
    `--outfile=${join(buildDir, 'harness.js')}`,
  ],
  { stdio: 'inherit' },
)

// --- 4. worker next to the bundle ------------------------------------------

copyFileSync(join(here, 'src/jvm.worker.js'), join(buildDir, 'jvm.worker.js'))
console.log('harness/build/: harness.js, jvm.worker.js')

// --- 5. the compiler ------------------------------------------------------

// CheerpJ's /app/ mount maps to the web server ROOT, and serve.mjs serves
// runtimes/java/, so the jar belongs here rather than in harness/.
if (!existsSync(join(here, 'ecj.jar'))) {
  console.error('\nMISSING ecj.jar -- run ./fetch-compiler.sh first (it is never committed).')
  process.exit(1)
}
console.log(`ecj.jar: ${statSync(join(here, 'ecj.jar')).size} bytes`)
