// GENERATED — do not edit. Source: JDK 17.0.19 reflection via
// runtimes/java/tools/gen-java-api.mjs. Regenerate: npm run gen:java-api
//
// Simple class name -> fully-qualified name, for the classes the editor's Java
// dictionaries reach for. The FQCNs used to be hand-typed in imports.ts.

export const JAVA_FQCN: Record<string, string> = {
  ArithmeticException: 'java.lang.ArithmeticException',
  ArrayDeque: 'java.util.ArrayDeque',
  ArrayIndexOutOfBoundsException: 'java.lang.ArrayIndexOutOfBoundsException',
  ArrayList: 'java.util.ArrayList',
  Arrays: 'java.util.Arrays',
  Boolean: 'java.lang.Boolean',
  BufferedReader: 'java.io.BufferedReader',
  BufferedWriter: 'java.io.BufferedWriter',
  Character: 'java.lang.Character',
  Collections: 'java.util.Collections',
  Collectors: 'java.util.stream.Collectors',
  Comparable: 'java.lang.Comparable',
  Comparator: 'java.util.Comparator',
  Deque: 'java.util.Deque',
  Double: 'java.lang.Double',
  Exception: 'java.lang.Exception',
  File: 'java.io.File',
  FileNotFoundException: 'java.io.FileNotFoundException',
  FileReader: 'java.io.FileReader',
  FileWriter: 'java.io.FileWriter',
  Files: 'java.nio.file.Files',
  HashMap: 'java.util.HashMap',
  HashSet: 'java.util.HashSet',
  IOException: 'java.io.IOException',
  IllegalArgumentException: 'java.lang.IllegalArgumentException',
  InputMismatchException: 'java.util.InputMismatchException',
  InputStreamReader: 'java.io.InputStreamReader',
  IntStream: 'java.util.stream.IntStream',
  Integer: 'java.lang.Integer',
  Iterable: 'java.lang.Iterable',
  Iterator: 'java.util.Iterator',
  LinkedHashMap: 'java.util.LinkedHashMap',
  LinkedHashSet: 'java.util.LinkedHashSet',
  LinkedList: 'java.util.LinkedList',
  List: 'java.util.List',
  Long: 'java.lang.Long',
  Map: 'java.util.Map',
  Math: 'java.lang.Math',
  NoSuchElementException: 'java.util.NoSuchElementException',
  NullPointerException: 'java.lang.NullPointerException',
  NumberFormatException: 'java.lang.NumberFormatException',
  Object: 'java.lang.Object',
  Objects: 'java.util.Objects',
  Optional: 'java.util.Optional',
  Path: 'java.nio.file.Path',
  Paths: 'java.nio.file.Paths',
  PrintStream: 'java.io.PrintStream',
  PrintWriter: 'java.io.PrintWriter',
  PriorityQueue: 'java.util.PriorityQueue',
  Queue: 'java.util.Queue',
  Random: 'java.util.Random',
  Runnable: 'java.lang.Runnable',
  RuntimeException: 'java.lang.RuntimeException',
  Scanner: 'java.util.Scanner',
  Set: 'java.util.Set',
  Stack: 'java.util.Stack',
  Stream: 'java.util.stream.Stream',
  String: 'java.lang.String',
  StringBuilder: 'java.lang.StringBuilder',
  System: 'java.lang.System',
  Thread: 'java.lang.Thread',
  TreeMap: 'java.util.TreeMap',
  TreeSet: 'java.util.TreeSet',
}
